### PR TITLE
[+] Add slf4j-simple & spacing fix

### PR DESCRIPTION
**Pull request by 128931**
slf4j-simple fixes the missing class error on startup and just changed from println to bukkit's logger to fix extra space in console when that was printed

### CODE REVIEW

**Comment by windcolor-dev** [comment]
The space fix LGTM :) What missing class error are you referring to?

**Comment by 128931** [comment]
> The space fix LGTM :) What missing class error are you referring to?

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

whenever u startup the spigot

**Comment by 128931** [comment]
> The space fix LGTM :) What missing class error are you referring to?

also, what's your Discord if u have it?

**Comment by windcolor-dev** [comment]
Ah, I see what you are talking about. The discord link is on the readme, just click the button on the top right of it.

**Pull request merged**
