### PR TITLE
Added MobSpawners settings

### PR DESCRIPTION
**Pull request by raccoman**
I recently worked on a Faction server and I needed to change the spawn rate of the spawners.
I thought it would be very useful, if there was an option to change the vanilla values of the spawners

### CODE REVIEW

**Comment by windcolor-dev** [comment]
This LGTM, is there any reason for removing Paper's configurable mob spawner tick rate?

**Comment by raccoman** [comment]
Yeah, it's useless with these settings

**Comment by windcolor-dev** [comment]
Oh, okay, thanks for adding these features :)

**Comment by windcolor-dev** [comment]
Oh, okay, thanks for adding these features :)

**Pull request merged**
